# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - 
        name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
          docker buildx create --use
          sudo apt install -y avahi-daemon
          sudo snap install node --classic
          sudo apt install -y npm
          sudo apt install -y jq
          sudo apt install git
          git clone --recursive https://github.com/Start9Labs/embassy-os.git
          cd embassy-os
          git submodule update --init --recursive
          make
